### ISSUE TITLE
Custom class standard array usage

### ISSUE THREAD

**Issue by tapir** [hideakitai/MsgPack#10]
I would like to convert below class to
```C
struct sc_sConfig {
  uint8_t channel;
  std::array<uint8_t, 4> xss;
  MSGPACK_DEFINE(channel, xss);
};
```
to
```C
struct sc_sConfig {
  uint8_t channel;
  uint8_t xss[4];
  MSGPACK_DEFINE(channel, xss);
};
```

The documentation mentions I need to serialize or pack, but I can't figure out what it means. Could you give an example?

Thank you

**Comment by hideakitai** [comment]
Hi, you can't do that. Please use the same struct (std::array <T, 4> instead of array[4])
