### ISSUE TITLE
Fails to compile on e.g. Arduino Mega 2560 due to INT5 macro

### ISSUE THREAD

**Issue by matthijskooijman** [hideakitai/MsgPack#2]
This bigger chip has more interrupts, so it defines [an `INT5` macro](https://github.com/vancegroup-mirrors/avr-libc/blob/06cc6ff5e6120b36f1b246871728addee58d3f87/avr-libc/include/avr/iomxx0_1.h#L321), which conflicts with Types.h:

```
.../MsgPack/MsgPack/Types.h:163:9: error: expected identifier before numeric constant
         INT5 = 0xE0, // same as NEGATIVE_FIXINT
```

This is really one of the reasons macros, especially such short ones, suck, but well, here we are. I can see two ways to fix this:
 - `#undef INT5` in `Types.h`. This is easy, but probably breaks some code out there that needs this particular bit *and* includes `MsgPack.h`
 - Rename the constant to something else that doesn't conflict. I *think* this does not change any public API, so this would probably be the preferred option.

To reproduce, compile the following sketch for the Arduino Mega 2560:

```
#include <MsgPack.h>
void setup() { }
void loop() { }
```

**Comment by matthijskooijman** [comment]
I wanted to try fixing this in a PR by renaming `INT5` in `Types.h`, but I'm unsure what kind of rename would be preferable. Just renaming `INT5` is probably not ideal, since that breaks the naming convention that is not consistently used. You could rename all of them to e.g. `INT_5` or `INT5BITS` maybe? Or just used `NEGATIVE_FIXINT` instead of `INT5` everwhere (and then maybe keep `INT5` as well, but put it in an `#if !defined(INT5)` block)? For consistency, maybe also use `POSITIVE_FIXINT` instead of `UINT7`, then?

**Comment by hideakitai** [comment]
Ah, this is always annoying problem on Arduino... I always use `#undef` and replace it with `static constexepr`. Because my `INT5` is namespaced with `enum class`, so making `#define INT5` to a static constant in global space can solve the problem. Can you check [this branch](https://github.com/hideakitai/MsgPack/tree/fix_int5_on_mega) works?

**Comment by matthijskooijman** [comment]
Hah, making it a constant, that's a clever trick. However, you are hardcoding the value to `5` now, which is a bit of an assumption (probably always true, but still). I don't think it's needed either, see PR #4 I just created. That additionally adds a `#define INT5 INT5`, which makes sure that any code the does `#ifdef INT5` still works.

**Comment by hideakitai** [comment]
Cool, I'll merge your PR. Thanks :)
