### ISSUE TITLE
Sending a int 0 presents a problem

### ISSUE THREAD

**Issue by MythicalForce** [hideakitai/MsgPack#6]
Qt side
```c++
sendBinary("colorPicker", 0);
```
Qt Output
```
[SOCKET][BINARY][ "colorPicker" ] QVariant(int, 0)
Binary Data :  "\x81\xAB""colorPicker\x00"
```

ESP32 side
```c++
                if ( mIndata["colorPicker"] )
                {
                    Serial.print("Color Picker : ");
                    Serial.print((int)mIndata["colorPicker"]);
                    Serial.println(" ");

                    if (_isAllStripsSelected == true)
                    {
                        for (int i = 1; i < 9; i++)
                        {
                            Strips[i]->Color.Picker = (int)mIndata["colorPicker"];
                        }
                    }
                    else
                    {
                        Strips[_selectedStrip]->Color.Picker = (int)mIndata["colorPicker"];
                    }
                }
```
ESP32 Output
```
empty.........................................
```

im able to send any number (int) between 1 and 21341245918250125 but not 0

**Comment by hideakitai** [comment]
Thank you for reporting! Can you give me minimum full code which can reproduce it?

**Comment by MythicalForce** [comment]
> Thank you for reporting! Can you give me minimum full code which can reproduce it?

QT side
```c++
sendBinary("colorPicker", '0');

void MainWindow::sendBinary(QString text, QVariant args)
{
    _MsgPackMap.clear();
    _MsgPackMap.insert(text, args);
    _MsgPackArray = MsgPack::pack(_MsgPackMap);
    _socket.sendBinaryToStrip(_MsgPackArray);
}

void Socket::sendBinaryToStrip(const QByteArray data)
{
    m_webSocket.sendBinaryMessage(data);
}
```

ESP32 Side
```c++
MsgPack::Unpacker unpacker;
MsgPack::map_t<String, int> mIndata;

// arduinoWebSocket
    switch ( type )
    {
        case WStype_BIN:
            if (unpacker.feed( payload, length ))
            {
                unpacker.deserialize( mIndata );
                
                if ( mIndata["colorPicker"] )
                {
                    Serial.print("Color Picker : ");
                    Serial.print((int)mIndata["colorPicker"]);
                    Serial.println(" ");

                    if (_isAllStripsSelected == true)
                    {
                        for (int i = 1; i < 9; i++)
                        {
                            Strips[i]->Color.Picker = (int)mIndata["colorPicker"];
                        }
                    }
                    else
                    {
                        Strips[_selectedStrip]->Color.Picker = (int)mIndata["colorPicker"];
                    }
                }
            }
        break;
        case WStype_FRAGMENT_TEXT_START:
        case WStype_FRAGMENT_BIN_START:
        case WStype_FRAGMENT:
        case WStype_FRAGMENT_FIN:

        default:
        break;
    }
```

**Comment by hideakitai** [comment]
@MythicalForce Hmm, following code works fine. And serialized binary is 

```
msgpack test start
81 AB 63 6F 6C 6F 72 50 69 63 6B 65 72 0 
colorPicker : 0
msgpack test success
```

```C++
#include <MsgPack.h>

MsgPack::map_t<String, int> m_in;
MsgPack::map_t<String, int> m_out;

void setup() {
    Serial.begin(115200);
    delay(2000);

    Serial.println("msgpack test start");

    m_in["colorPicker"] = 0;

    MsgPack::Packer packer;
    packer.serialize(m_in);

    // show serialized data
    for (size_t i = 0; i < packer.size(); ++i) {
        Serial.print(packer.data()[i], HEX);
        Serial.print(" ");
    }
    Serial.println();

    MsgPack::Unpacker unpacker;
    if (unpacker.feed(packer.data(), packer.size())) {
        unpacker.deserialize(m_out);
        Serial.print("colorPicker : ");
        Serial.println(m_out["colorPicker"]);
    }

    if (m_in != m_out) {
        Serial.println("failed: map<string, int>");
    } else {
        Serial.println("msgpack test success");
    }
}

void loop() {
}
```

Could you show me your received binary data in HEX? The final zero in the payload is fed to unpacker correctly?

**Comment by MythicalForce** [comment]
So sending the number 0
Qt Side
```
[SOCKET][BINARY][ "colorPicker" ] QVariant(int, 0)
Binary Data :  "\x81\xAB""colorPicker\x00"
Binary Length :  14
```
ESP32 Side
```
[HEXDUMP] Address: 0x3FFD4D9C len: 0xE (14)
[0x3FFD4D9C] 0x00000000: 81 AB 63 6F 6C 6F 72 50 69 63 6B 65 72 00 
Binary : ��colorPicker
Payload Length : 14
```

**Comment by hideakitai** [comment]
@MythicalForce I don't know why but your zero is serialized as char in Qt. But you are deserializing it as int in Arduino.
Please fix it to send zero as int from Qt.

**Comment by MythicalForce** [comment]
> @MythicalForce I don't know why but your zero is serialized as char in Qt. But you are deserializing it as int in Arduino.
> Please fix it to send zero as int from Qt.

yea i updated! the above output! :) i tested sending a stringed 0... but no results

**Comment by hideakitai** [comment]
What is your received data? Is it correct? Please print the payload in length as hex.

**Comment by MythicalForce** [comment]
> What is your received data? Is it correct? Please print the payload in length as hex.

this is the data hex dump of payload
```
[HEXDUMP] Address: 0x3FFD4D9C len: 0xE (14)
[0x3FFD4D9C] 0x00000000: 81 AB 63 6F 6C 6F 72 50 69 63 6B 65 72 00 
```
this is the raw Serial print of payload `Serial.printf("Binary : %s\n", payload);`
```
Binary : ��colorPicker
```
and the payload length
```
Payload Length : 14
```

**Comment by hideakitai** [comment]
Ah sorry, it is same as my example, so it should be deserialized correctly. Can you check your code again based on my example?

**Comment by MythicalForce** [comment]
@hideakitai oh and msgpack does not give anything....
i have this
```
                    Serial.print("Color Picker : ");
                    Serial.print((int)mIndata["colorPicker"]);
                    Serial.println(" ");
```
but it NEVER fires if i send `int 0`.... if i send any other number this fires with no problem

**Comment by MythicalForce** [comment]
> Ah sorry, it is same as my example, so it should be deserialized correctly. Can you check your code again based on my example?

and they are not the same notice at the end mine has `00` and yours has `0`

**Comment by hideakitai** [comment]
@MythicalForce 

- Try if my example above works correctly in your environment
- Enable debug output and see the debug log

```C++
#define MSGPACK_DEBUGLOG_ENABLE
#include <MsgPack.h>
```

> they are not the same notice at the end mine has 00 and yours has 0

What is the difference? Isn't it zero in integer?

**Comment by MythicalForce** [comment]
> @MythicalForce
> 
> * Try if my example above works correctly in your environment
> * Enable debug output and see the debug log
> 
> ```c++
> #define MSGPACK_DEBUGLOG_ENABLE
> #include <MsgPack.h>
> ```
> 
> > they are not the same notice at the end mine has 00 and yours has 0
> 
> What is the difference? Isn't it zero in integer?

the difference is that i have a **Null Termination** at the end **\0** and then my **0** so it terminates right after **\0** so the 0 escapes

**Comment by hideakitai** [comment]
> the difference is that i have a Null Termination at the end \0 and then my 0 so it terminates right after \0 so the 0 escapes

Sorry, I couldn't understand what you mean... MessagePack protocol doesn't have null termination for String type and zero is deserialized as Integer zero. Please see the [spec](https://github.com/msgpack/msgpack/blob/master/spec.md) for the detail.

Even if it means that the input binary data array is `char`, it can be deserialized correctly as follows (`feed()` can't accept `char*` and it will cause compile error, so you should cast `char*` to `uint8_t*`).

```C++
#include <MsgPack.h>

static constexpr size_t data_size = 14;
uint8_t data_in_uint8[data_size] {0x81, 0xAB, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x50, 0x69, 0x63, 0x6B, 0x65, 0x72, 0x00};
char data_in_char[data_size] {0x81, 0xAB, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x50, 0x69, 0x63, 0x6B, 0x65, 0x72, 0x00};

void setup() {
    Serial.begin(115200);
    delay(2000);

    Serial.println("msgpack test start");

    Serial.print("test input uint8: ");
    {
        MsgPack::map_t<String, int> m_out;
        MsgPack::Unpacker unpacker;
        if (unpacker.feed(data_in_uint8, data_size)) {
            unpacker.deserialize(m_out);
            Serial.print("success => m_out[colorPicker] = ");
            Serial.println(m_out["colorPicker"]);
        } else {
            Serial.println("failed");
        }
    }

    Serial.print("test input char : ");
    {
        MsgPack::map_t<String, int> m_out;
        MsgPack::Unpacker unpacker;
        if (unpacker.feed((uint8_t*)data_in_char, data_size)) {
            unpacker.deserialize(m_out);
            Serial.print("success => m_out[colorPicker] = ");
            Serial.println(m_out["colorPicker"]);
        } else {
            Serial.println("failed");
        }
    }

    Serial.println("msgpack test finish");
}

void loop() {
}
```

Anyway, I can't go further if you can't try these,

> - Try if my example above works correctly in your environment
> - Enable debug output and see the debug log

I can't reproduce the problem. And this library works fine for your binary array so I think there is no problem for this library. Please check again your binary packet has the correct data and size.

**Comment by MythicalForce** [comment]
@hideakitai im sorry to have wasted your time! it was my fault all along!

someone pointed out to me that this if statement will fail if value associated with colorPicker equals 0!
`if ( mIndata["colorPicker"] )`

so i changed it to

`if ( mIndata.find("colorPicker") != mIndata.end() )`
