### ISSUE TITLE
pack std::pair bug

### ISSUE THREAD

**Issue by dstahlke** [hideakitai/MsgPack#7]
Shouldn't the array size be 2 here?  In MsgPack/MsgPack/Packer.h:

            void pack(const std::pair<T, U>& arr) {
                packArraySize(1);
                pack(arr.first);
                pack(arr.second);
            }

**Comment by hideakitai** [comment]
Oh, that's right.  I'll fix it by the end of today.  By the way, what library did you test with this library?

**Comment by hideakitai** [comment]
Thank you for reporting. Fixed in v0.3.10. Please try it again :)

**Comment by dstahlke** [comment]
"By the way, what library did you test with this library?" -> I was using MsgPack on its own, in Arduino.  I actually wasn't even using std::pair, I just happened to see that while browsing through the header.  Thanks for the quick fix.
