### ISSUE TITLE
Improve performance - add Packer constructor with a capacity parameter for the underlying buffer

### ISSUE THREAD

**Issue by jeronimoyk** [hideakitai/MsgPack#8]
https://github.com/hideakitai/MsgPack/blob/9f7696f796ff927561b35174d2b713fe64407053/MsgPack/Packer.h#L39

something like:

Packer() {}
Packer(uint32_t capacity) { buffer.reserve(capacity); }

Depending on the size of the message, the performance improvement can be significant.

**Comment by jeronimoyk** [comment]
The same for the Unpacker and indices capacity. :)

**Comment by hideakitai** [comment]
@ykraynov Thank you for the proposal! I've added it in v0.3.13. Please try it.
